require('matoch.settings')
require('matoch.plugins')
require('matoch.myfunctions')
require('matoch.maps')
require('matoch.lsp')
require('matoch.cmp')
require('matoch.statusline')
require('matoch.winbar')
