local Plug = vim.fn['plug#']
vim.call('plug#begin', '~/.vim/plugged')
Plug('airblade/vim-gitgutter')
Plug('autozimu/LanguageClient-neovim', { branch = 'next', ['do'] = 'bash install.sh'})
Plug('frazrepo/vim-rainbow')
Plug('gruvbox-community/gruvbox')
Plug('junegunn/fzf')
Plug('machakann/vim-highlightedyank')
-- Plug('neoclide/coc.nvim', {branch = 'release'})
Plug('neovim/nvim-lspconfig')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-lua/popup.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-telescope/telescope-fzf-native.nvim', {['do']= 'make' })
Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
Plug('preservim/nerdtree')
Plug('sk1418/join')
Plug('ThePrimeagen/harpoon')
Plug('tpope/vim-commentary')
Plug('tpope/vim-fugitive')
Plug('tpope/vim-surround')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('L3MON4D3/LuaSnip')
Plug('saadparwaiz1/cmp_luasnip')
vim.call('plug#end')
vim.cmd("colorscheme gruvbox")
vim.cmd('highlight WinSeparator guibg=None')
vim.cmd('let g:rainbow_active = 1')

