vim.g.mapleader = ' '
vim.o.autoread = true
vim.o.backup = false
vim.o.colorcolumn = 80
vim.o.errorbells = false
vim.o.expandtab = true
vim.o.hidden = true
vim.o.history = 1000
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.inccommand = split
vim.o.incsearch = true
vim.o.laststatus = 3
vim.o.list = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.shiftwidth = 4
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.softtabstop = 4
vim.o.swapfile = false
vim.o.tabstop = 4 
vim.o.textwidth = 120
vim.o.visualbell = true
vim.o.wrap = false

vim.opt.encoding = 'utf-8'
vim.opt.listchars = {tab = '▸·▸', eol = '⏎', trail = '┈', extends = '…', precedes = '…', nbsp = '☠', lead = '·'}
vim.opt.showbreak = '^'
vim.opt.undodir = os.getenv("HOME") .. "/.vim/nvimundodir"
vim.opt.undofile = true
vim.wo.signcolumn = 'yes:1'
